FROM alpine
RUN apk add --no-cache python3 py3-pip ffmpeg sqlite bash
RUN pip install --no-cache-dir celery flower

RUN apk update
RUN apk upgrade

RUN mkdir -p /boil_watch
RUN mkdir -p /boil_hold
RUN mkdir -p /Boilest
RUN mkdir -p /Scripts
COPY /Scripts /Scripts
WORKDIR "/Scripts"

EXPOSE 80
EXPOSE 5555

#CMD ["celery", "-A", "tasks", "worker", "-l", "INFO", "-c", "1"]
#RUN chmod +x /Scripts/celery.sh
#Run [/Scripts/celery.sh]    
#CMD ["celery", "-A", "tasks", "worker", "-l", "INFO", "-c", "1", "&", "celery", "-A", "tasks", "flower", "-l", "INFO"]
#ENTRYPOINT [ "/bin/bash", "-l", "-c" ]
#CMD ["python3", "/Scripts/Celery.py"]

ENTRYPOINT [ "/bin/sh"]
CMD ["/Scripts/Celery.sh"]