FROM alpine
RUN apk add --no-cache python3 py3-pip ffmpeg sqlite bash tzdata
RUN pip install --no-cache-dir --root-user-action=ignore celery flower requests Flask

ENV TZ=US/Pacific

RUN apk update
RUN apk upgrade

# Need to set UID/GID since we're likely interfacing with files owned by a non-root user
ARG UID=1000
ARG GID=1000


RUN mkdir -p /boil_hold
RUN mkdir -p /Boilest
RUN mkdir -p /Boilest/DB
RUN mkdir -p /Boilest/Configurations
RUN mkdir -p /Scripts

RUN mkdir -p /Media
RUN mkdir -p /Anime_TV
RUN mkdir -p /Aime_Movies
RUN mkdir -p /Live_Action_TV
RUN mkdir -p /Live_Action_Movies
RUN mkdir -p /Animated_TV
RUN mkdir -p /Animated_Movies

COPY /Scripts /Scripts
COPY /Scripts/DB /Boilest/DB
WORKDIR "/Scripts"

ENV Manager no

# Add a user that is the same user group as the data being read
# Is this clean?  Not really...  Will need to revisit this later

RUN addgroup -g 1000 boil 
RUN adduser -D boil -G boil -u 1000
RUN chown -R boil:boil /boil_hold /Boilest /Scripts
USER boil

EXPOSE 5000
EXPOSE 5555


ENTRYPOINT [ "/bin/sh"]
CMD ["/Scripts/Celery.sh"]