name: Publish Docker Image to GHCR

on:
  push

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set image tag
        id: set-tag
        run: |
          if [ "${{ github.ref_name }}" == "dev" ]; then
            echo "tag=dev" >> $GITHUB_OUTPUT
          else
            echo "tag=v1.1" >> $GITHUB_OUTPUT
          fi      
      - name: Build and push the image
        run: |
          docker login --username goingoffroading --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/goingoffroading/boilest:${{ steps.set-tag.outputs.tag }}
          docker push ghcr.io/goingoffroading/boilest:${{ steps.set-tag.outputs.tag }}